// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu8gvNYCbF25wL5mc0WUoZh3UCCaHSvIQ',
    appId: '1:535164306658:web:69f77aa129b037884f0abb',
    messagingSenderId: '535164306658',
    projectId: 'salon-booking-app-b8939',
    authDomain: 'salon-booking-app-b8939.firebaseapp.com',
    storageBucket: 'salon-booking-app-b8939.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDh0L68a9JILuVFig5EqbXVkkHVNZ-jupA',
    appId: '1:535164306658:android:d0b1e325318b53e44f0abb',
    messagingSenderId: '535164306658',
    projectId: 'salon-booking-app-b8939',
    storageBucket: 'salon-booking-app-b8939.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFV6sATFN9XkPJM73LKGbYxfq-chX7Ylg',
    appId: '1:535164306658:ios:4fabab719d6545044f0abb',
    messagingSenderId: '535164306658',
    projectId: 'salon-booking-app-b8939',
    storageBucket: 'salon-booking-app-b8939.firebasestorage.app',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFV6sATFN9XkPJM73LKGbYxfq-chX7Ylg',
    appId: '1:535164306658:ios:4fabab719d6545044f0abb',
    messagingSenderId: '535164306658',
    projectId: 'salon-booking-app-b8939',
    storageBucket: 'salon-booking-app-b8939.firebasestorage.app',
    iosBundleId: 'com.example.salonApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu8gvNYCbF25wL5mc0WUoZh3UCCaHSvIQ',
    appId: '1:535164306658:web:5743efb5f0c4b0de4f0abb',
    messagingSenderId: '535164306658',
    projectId: 'salon-booking-app-b8939',
    authDomain: 'salon-booking-app-b8939.firebaseapp.com',
    storageBucket: 'salon-booking-app-b8939.firebasestorage.app',
  );
}
